---
## This template creates a public hosted zone in Route53.

AWSTemplateFormatVersion: '2010-09-09'
Description: 'DOC Data Service Template - Route53 Public Hosted Zone'

## ::METADATA::
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    #---------------
      - Label: 
          default: "General Configuration"
        Parameters:
          - environment
          - serviceName      

    ParameterLabels:
    #---------------  
      # General Configuration

      environment:
        default: "Environment:"
      serviceName:
        default: 'Service name'

## ::PARAMETERS::
Parameters:

  # General Parameters

  environment:
    Type: String
    AllowedValues:
    - "Example"
    Default: "Example"

  serviceName:
    Type: String
    ConstraintDescription: 'Must be between 3 - 32 characters long.'
    AllowedPattern: "^[A-Za-z0-9-]{3,32}$"
    MinLength: 3
    MaxLength: 32
    Default: 'unknownservicename'

## ::MAPPINGS::  
Mappings:
  # Environment-Specific Config
  EnvConfig:
    Example:
      EnvToLower: 'example'
      AccountPrefix: 'exampleprefix'
      DomainPrefix: 'example.'

## ::RESOURCES::
Resources:

  # Route 53 Hosted Zone
  HostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      HostedZoneConfig:
        Comment: !Sub "Public hosted zone for data services in the ${environment}. Add new records here."
      Name: !Sub 
        - '${env}${service}.example.org'
        - { 
            env: !FindInMap [ EnvConfig, !Ref environment, DomainPrefix ],
            service: !Ref serviceName
          }

## SSM PARAMETERS

  # Hosted Zone Name
  HostedZoneName:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: !Sub "Name of the Public hosted zone for the ${serviceName} service in the ${environment} environment"
      Name: !Sub
        - '/${env}/${service}/route53/public-zone/name'
        - {
          env: !FindInMap [ EnvConfig, !Ref environment, EnvToLower ],
          service: !Ref serviceName
          }
      Type: 'String'
      Value: !Sub 
        - '${env}${service}.example.org'
        - { 
            env: !FindInMap [ EnvConfig, !Ref environment, DomainPrefix ],
            service: !Ref serviceName
          }
      # Tag Config
      Tags:        
        Service: !Sub '${serviceName}'
        Environment: !Ref environment

  # Hosted Zone ID
  HostedZoneId:
    Type: AWS::SSM::Parameter
    Properties: 
      Description: !Sub "ID of the Public hosted zone for the ${serviceName} service in the ${environment} environment"
      Name: !Sub
        - '/${env}/${service}/route53/public-zone/id'
        - {
          env: !FindInMap [ EnvConfig, !Ref environment, EnvToLower ],
          service: !Ref serviceName
          }
      Type: 'String'
      Value: !Ref HostedZone
      # Tag Config
      Tags:        
        Service: !Sub '${serviceName}'
        Environment: !Ref environment  

## ::OUTPUTS::
Outputs:

  TemplateID:
    Description: 'Template id'
    Value: 'vpc/zone-private'

  StackName:
    Description: 'Stack name'
    Value: !Sub '${AWS::StackName}'

# --

  HostedZoneName:
    Description: 'The name of the hosted zone.'
    Value: !Sub
      - '${env}${service}.example.org'
      - { 
          env: !FindInMap [ EnvConfig, !Ref environment, DomainPrefix ],
          service: !Ref serviceName
        }
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneName'

  HostedZoneId:
    Description: 'The ID of the hosted zone.'
    Value: !Ref HostedZone
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneId'