---
## This template creates CI/CD Pre-requisites

AWSTemplateFormatVersion: '2010-09-09'
Description: 'DOC Data Service Template - CI/CD Pre-requisites'

## ::METADATA::
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups: 
    #---------------
      - Label: 
          default: "General Configuration"
        Parameters:
          - serviceName
          - exampleAccountNumber
      - Label:
          default: 'Deployment Configuration'
        Parameters:
          - crossAccountCondition
          
    ParameterLabels:
    #---------------  
      # General Parameters

      serviceName:
        default: "Data Service name:"
      
      exampleAccountNumber:
        default: "Example account number:"

      # Deployment Parameters

      crossAccountCondition:
        default: "Create cross-account resources?"

## ::PARAMETERS::
Parameters:

  # General Parameters

  serviceName:
    Type: String
    ConstraintDescription: 'Must be between 3 - 32 characters long.'
    AllowedPattern: "^[A-Za-z0-9]{3,32}$"
    MinLength: 4
    MaxLength: 32
    Default: "unknowndataservice"

  exampleAccountNumber:
    Description: "12-digit AWS Account number for Example account"
    Type: Number
    Default: 0000000000

  # Deployment Configuration

  crossAccountCondition:
    Description: "Conditionally creates the resources for cross account access"
    Type: String    
    Default: 'false'
    AllowedValues: 
      - 'true'
      - 'false'

## ::CONDITIONS::    
Conditions:
  CreateCrossAccountResources: !Equals [ !Ref crossAccountCondition, true ]

## ::MAPPINGS::  
Mappings:
  # Environment-Specific Config
  EnvConfig:
    Example:
      EnvToLower: 'example'
      AccountPrefix: 'exampleprefix'

## ::RESOURCES::
Resources:

  ## ===================================
  ## ENCRYPTION
  ## ===================================

  # KMS Key
  KMSKey:
    Type: "AWS::KMS::Key"
    Properties:
      Description: "Used by Assumed Roles in Example/Test/Uat/Prod accounts to Encrypt/Decrypt code"
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Id: !Ref "AWS::StackName"
        Statement:
          # Admin
          - Sid: "Allows admin of the key"
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
            Resource: "*"
          # Lambda Functionality
          - Sid: "Allow use of the key for CryptoGraphy Lambda"
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${exampleAccountNumber}:root"
                - !If
                  - CreateCrossAccountResources
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/${serviceName}-service-codepipeline-execution
                  - !Ref AWS::NoValue   
                - !If
                  - CreateCrossAccountResources
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/${serviceName}-service-apitest-execution
                  - !Ref AWS::NoValue                              
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"

  # KMS Key Alias          
  KMSAlias:
    Type: "AWS::KMS::Alias"
    Properties:
      AliasName: !Sub "alias/${serviceName}/codepipeline-crossaccounts"
      TargetKeyId: !Ref KMSKey
  
  ## ===================================
  ## SUPPORT INFRA
  ## ===================================

  # CodePipeline Artifact Bucket
  # This contains all the artifacts generated by the CodePipeline
  PipelineArtifactBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      # Lifecycle Config
      LifecycleConfiguration:
        Rules:
          - Status: 'Enabled'
            Id: 'main-lifecycle-rule'
            ExpirationInDays: 366

  # Test Result Bucket
  # This contains results from various third-party test tools.
  # Versioning is turned on - we'll overwrite with test results
  # and ensure we maintain the history.
  TestingResultsBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      # Lifecycle Config
      LifecycleConfiguration:
        Rules:
          - Status: 'Enabled'
            Id: 'main-lifecycle-rule'
            ExpirationInDays: 366
      VersioningConfiguration:
        Status: Enabled            

## ::OUTPUTS::
Outputs:

  TemplateID:
    Description: 'Template id'
    Value: 'cicd/service-prereqs'
  
  StackName:
    Description: 'Stack name'
    Value: !Sub '${AWS::StackName}'

  ## ===================================
  ## ENCRYPTION
  ## ===================================

  KMSKeyArn:
    Description: 'Data service KMS Key - ARN'
    Value: !GetAtt "KMSKey.Arn"
    Export:
      Name: !Sub "${AWS::StackName}-KMSKey-ARN"

  ## ===================================
  ## SUPPORT INFRA
  ## ===================================

  PipelineArtifactBucket:
    Description: "Pipeline artifact bucket - Name"
    Value: !Ref PipelineArtifactBucket
    Export:
      Name: !Sub "${AWS::StackName}-PipelineArtifactBucket-Name"

  PipelineArtifactBucketArn:
    Description: "Pipeline artifact bucket - ARN"
    Value: !GetAtt "PipelineArtifactBucket.Arn"
    Export:
      Name: !Sub "${AWS::StackName}-PipelineArtifactBucket-ARN"

  TestingResultsBucket:
    Description: "Testing results bucket - Name"
    Value: !Ref "TestingResultsBucket"
    Export:
      Name: !Sub "${AWS::StackName}-TestingResultsBucket-Name"

  TestingResultsBucketArn:
    Description: "Testing results bucket - ARN"
    Value: !GetAtt "TestingResultsBucket.Arn"
    Export:
      Name: !Sub "${AWS::StackName}-TestingResultsBucket-ARN"      