---
## This template creates an hosted zone in Route53.

AWSTemplateFormatVersion: '2010-09-09'
Description: 'DOC Data Service Template - Route53 Private Hosted Zone'

## ::METADATA::
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    #---------------
      - Label: 
          default: "General Configuration"
        Parameters:
          - environment
      
      - Label: 
          default: "Network Configuration"
        Parameters:
          - vpcId

    ParameterLabels:
    #---------------  
      # General Configuration

      environment:
        default: "Environment:"

      # Network Configuration

      vpcId:
        default: "VPC ID:"

## ::PARAMETERS::
Parameters:

  # General Parameters

  environment:
    Type: String
    AllowedValues:
    - "Example"
    Default: "Example"

  # Network Configuration

  vpcId:
    Type: "AWS::EC2::VPC::Id"

## ::MAPPINGS::  
Mappings:
  # Environment-Specific Config
  EnvConfig:
    Example:
      EnvToLower: 'example'
      AccountPrefix: 'docnzexample'

## ::RESOURCES::
Resources:

  # Route 53 Private Hosted Zone
  HostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      HostedZoneConfig:
        Comment: !Sub "Private hosted zone for data services in the ${environment}. Add new records here."
      Name: !Sub 
        - "${Env}.internal.example.org"
        - {
            Env: !FindInMap [ EnvConfig, !Ref environment, EnvToLower ]
          }
      VPCs:
      - 
        VPCId: !Ref "vpcId"
        VPCRegion: !Ref "AWS::Region"

## ::OUTPUTS::
Outputs:

  TemplateID:
    Description: 'Template id'
    Value: 'vpc/zone-private'

  StackName:
    Description: 'Stack name'
    Value: !Sub '${AWS::StackName}'

  HostedZoneName:
    Description: 'The name of the hosted zone.'
    Value: !Sub 
        - "${Env}.internal.example.org"
        - {
            Env: !FindInMap [ EnvConfig, !Ref environment, EnvToLower ]
          }
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneName'

  HostedZoneId:
    Description: 'The ID of the hosted zone.'
    Value: !Ref HostedZone
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneId'